apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.2.0 (99f88ef)
  creationTimestamp: null
  labels:
    io.kompose.service: api-gateway
  name: api-gateway
  namespace: spring-pet-clinic
spec:
  replicas: 5
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: api-gateway
    spec:
      containers:
      - image: odedia/spring-petclinic-api-gateway
        name: api-gateway
        livenessProbe:
          httpGet:
            port: 8080
            path: /actuator/health
          initialDelaySeconds: 60
          periodSeconds: 2
        readinessProbe:
          httpGet:
            port: 8080
            path: /actuator/health
          initialDelaySeconds: 15
        resources:
          limits:
            memory: 1Gi
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: kubernetes
        - name: MANAGEMENT_METRICS_EXPORT_WAVEFRONT_APITOKEN
          valueFrom:
             secretKeyRef:
               name: wavefront
               key: token
        - name: MANAGEMENT_METRICS_EXPORT_WAVEFRONT_URI
          valueFrom:
             secretKeyRef:
               name: wavefront
               key: uri
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
