apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.2.0 (99f88ef)
  creationTimestamp: null
  labels:
    io.kompose.service: visits-service
  name: visits-service
spec:
  replicas: 10
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: visits-service
    spec:
      containers:
      - image: odedia/spring-petclinic-visits-service
        name: visits-service
        livenessProbe:
          httpGet:
            port: 8761
            path: /actuator/health
          initialDelaySeconds: 40
          periodSeconds: 2
        readinessProbe:
          httpGet:
            port: 8761
            path: /actuator/health
          initialDelaySeconds: 15
        resources:
          limits:
            memory: 1Gi
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: k8s
        ports:
        - containerPort: 8082
        resources: {}
      restartPolicy: Always
status: {}
